import { Router } from 'express';
import tarefaController from '../controllers/tarefaController.js';
import solicitacaoController from '../controllers/solicitacaoController.js';
import recorteController from '../controllers/recorteController.js';
import automacaoController from '../controllers/automacaoController.js';
const router = Router();
router.get('/tarefas', tarefaController.listar);
router.get('/tarefas/catalogo', tarefaController.catalogo);
router.get('/tarefas/ia/configuracao', solicitacaoController.configuracao);
router.post('/tarefas/email/testar', automacaoController.testarSMTP);
router.post('/tarefas/setores', tarefaController.setor);
router.post('/tarefas/fluxos', tarefaController.fluxo);
router.post('/tarefas', tarefaController.salvar);
router.get('/tarefas/:id', tarefaController.detalhe);
router.put('/tarefas/:id', tarefaController.salvar);
router.post('/tarefas/:id/documentos', tarefaController.anexar);
router.post('/tarefas/:id/solicitacoes', tarefaController.solicitar);
router.get('/tarefas/:id/solicitacoes/:solicitacaoId/analise', solicitacaoController.consultar);
router.get('/tarefas/:id/solicitacoes/:solicitacaoId/automacao', automacaoController.resumo);
router.post('/tarefas/:id/solicitacoes/:solicitacaoId/periodos/:periodoId/contato', automacaoController.contato);
router.get('/tarefas/:id/solicitacoes/:solicitacaoId/periodos/:periodoId/mensagem', automacaoController.mensagem);
router.put('/tarefas/:id/solicitacoes/:solicitacaoId/periodos/:periodoId/mensagem', automacaoController.salvarMensagem);
router.post('/tarefas/:id/solicitacoes/:solicitacaoId/periodos/:periodoId/mensagem/enviar', automacaoController.enviar);
router.post('/tarefas/:id/solicitacoes/:solicitacaoId/analise', solicitacaoController.executar);
router.put('/tarefas/:id/solicitacoes/:solicitacaoId/analise', solicitacaoController.revisar);
router.get('/tarefas/:id/solicitacoes/:solicitacaoId/recortes', recorteController.listar);
router.post('/tarefas/:id/solicitacoes/:solicitacaoId/recortes', recorteController.criar);
router.get('/tarefas/:id/solicitacoes/:solicitacaoId/ctps/:documentoId/paginas/:pagina', recorteController.visualizarFonte);
router.get('/tarefas/:id/solicitacoes/:solicitacaoId/recortes/:recorteId/paginas/:pagina', recorteController.visualizarRecorte);
router.get('/tarefas/:id/solicitacoes/:solicitacaoId/recortes/:recorteId/pdf', recorteController.baixar);
router.post('/tarefas/:id/solicitacoes/:solicitacaoId/recortes/:recorteId/aprovar', recorteController.aprovar);
router.patch('/tarefas/:id', tarefaController.alterarSituacao);
export default router;
